### ISSUE TITLE
Connection to variant validator

### ISSUE THREAD

**Issue by yoannvial** [beboche/MobiDetails#31]
there seems to be a connection problem with the variant validator on the web interface. In the example below I had to enter the variant several times to get the result.
![ScreenShotMD](https://user-images.githubusercontent.com/61030265/194536481-d4635761-7223-4717-8ae5-fff3ebc1b67a.jpg)

**Comment by beboche** [comment]
Hi, thanks for reporting, no explanation at the time, VV seems to work fine, variants are correctly annotated on the dev servers, but on the prod I have some issues like yours, from now and then today. Investigating.

**Comment by beboche** [comment]
Highly likely related to

https://github.com/openvar/variantValidator/issues/421

issue still active

**Comment by beboche** [comment]
tried to solve this issue by setting up 2 internal VV servers - however the issue still occurs

waiting for @Peter-J-Freeman to check

https://github.com/advisories/GHSA-m2qf-hxjv-5gpq

which could be the cause.

**Comment by Peter-J-Freeman** [comment]
Ive updated the entire environment and flask to a patched version.

**Comment by beboche** [comment]
> Ive updated the entire environment and flask to a patched version.

Hi @Peter-J-Freeman , thanks.

Is it online?
If so I might switch back my requests to your server and see what happens.

**Comment by Peter-J-Freeman** [comment]
Yes. I made it live last night. Was late so no testing. Let me know if anything breaks

**Comment by beboche** [comment]
Hi @Peter-J-Freeman ,
Friday evening I switched all my queries to https://rest.variantvalidator.org/ (instead of my internal docker servers).

I've had many errors during the week end, but no obvious patterns. here are some examples:

1. this one occured several times (about 20-30 times) on saturday and sunday (the query was different from my side, but the answer and submitted variant remanied the same:

- query:
`
https://rest.variantvalidator.org/VariantValidator/variantvalidator/GRCh38/NM_003284.4:c.131G>C/NM_003284.4?content-type=application/json {'User-Agent': 'MobiDetails (mobidetails.iurc@gmail.com)'}
`

- VV answer:

```json
{"flag": "warning",
 "metadata": {"variantvalidator_hgvs_version": "2.2.0", "variantvalidator_version": "2.2.1.dev36+gaa87b97", "vvdb_version": "vvdb_2022_11", "vvseqrepo_db": "VV_SR_2022_11/master", "vvta_version": "vvta_2022_11_1"},
 "validation_warning_1": {
    "alt_genomic_loci": [],
    "annotations": {}, 
    "gene_ids": {}, 
    "gene_symbol": "", 
    "genome_context_intronic_sequence": "", 
    "hgvs_lrg_transcript_variant": "", 
    "hgvs_lrg_variant": "", 
    "hgvs_predicted_protein_consequence": {"lrg_slr": "", "lrg_tlr": "", "slr": "", "tlr": "" }, 
    "hgvs_refseqgene_variant": "", 
    "hgvs_transcript_variant": "", 
    "primary_assembly_loci": {}, 
    "reference_sequence_records": "", 
    "refseqgene_context_intronic_sequence": "", 
    "rna_variant_descriptions": None, 
    "selected_assembly": False, 
    "submitted_variant": "NM_005228.4, NR_047551.1:c.2315C>G", 
    "transcript_description": "", 
    "validation_warnings": ["Multiple ALT sequences detected: auto-submitting all possible combinations"], "variant_exonic_positions": None
    }
}
```

2. the second example is really weird: have a look at the submitted variant in validations_warning_1 and _2:

- query:

`
https://rest.variantvalidator.org/VariantValidator/variantvalidator/GRCh38/NM_000110.4:c.1733T>C/NM_000110.4?content-type=application/json {'User-Agent': 'MobiDetails (mobidetails.iurc@gmail.com)'}
`

- answer:

```json
{"flag": "warning", 
"metadata": {"variantvalidator_hgvs_version": "2.2.0", "variantvalidator_version": "2.2.1.dev36+gaa87b97", "vvdb_version": "vvdb_2022_11", "vvseqrepo_db": "VV_SR_2022_11/master", "vvta_version": "vvta_2022_11_1"},
"validation_warning_1": {
    "alt_genomic_loci": [], 
    "annotations": {}, 
    "gene_ids": {}, 
    "gene_symbol": "", 
    "genome_context_intronic_sequence": "", 
    "hgvs_lrg_transcript_variant": "", 
    "hgvs_lrg_variant": "", 
    "hgvs_predicted_protein_consequence": {"lrg_slr": "", "lrg_tlr": "", "slr": "", "tlr": ""}, 
    "hgvs_refseqgene_variant": "", 
    "hgvs_transcript_variant": "", 
    "primary_assembly_loci": {}, 
    "reference_sequence_records": "", 
    "refseqgene_context_intronic_sequence": "", 
    "rna_variant_descriptions": None, 
    "selected_assembly": "GRCh38", 
    "submitted_variant": "NM_000110.4:c.1733T>C", 
    "transcript_description": "", 
    "validation_warnings": [], 
    "variant_exonic_positions": None
    }, 
"validation_warning_2": {
    "alt_genomic_loci": [], 
    "annotations": {}, 
    "gene_ids": {}, 
    "gene_symbol": "", 
    "genome_context_intronic_sequence": "", 
    "hgvs_lrg_transcript_variant": "", 
    "hgvs_lrg_variant": "", 
    "hgvs_predicted_protein_consequence": {"lrg_slr": "", "lrg_tlr": "", "slr": "", "tlr": ""}, 
    "hgvs_refseqgene_variant": "", 
    "hgvs_transcript_variant": "", 
    "primary_assembly_loci": {}, 
    "reference_sequence_records": "", 
    "refseqgene_context_intronic_sequence": "", 
    "rna_variant_descriptions": None, 
    "selected_assembly": False, 
    "submitted_variant": "NM_005228.4, NR_047551.1:c.2315C>G", 
    "transcript_description": "", 
    "validation_warnings": ["Multiple ALT sequences detected: auto-submitting all possible combinations"], 
    "variant_exonic_positions": None
    }
}
```

3. a simple mix:

- query:

`
https://rest.variantvalidator.org/VariantValidator/variantvalidator/GRCh38/NM_001009944.3:c.10970C>T/NM_001009944.3?content-type=application/json {'User-Agent': 'MobiDetails ([mobidetails.iurc@gmail.com])'}
`

- answer:

```
{"NM_005228.3:c.2236_2250del": 
    {"alt_genomic_loci": [], 
    "annotations": ...
```

4. also some empty results (this morning):

- query:
`
https://rest.variantvalidator.org/VariantValidator/variantvalidator/GRCh38/NM_175058.5:c.1946G>C/all?content-type=application/json {'User-Agent': 'MobiDetails (mobidetails.iurc@gmail.com)'}
`

- answer:

```json
{"flag": "empty_result", 
"metadata": {"variantvalidator_hgvs_version": "2.2.0", "variantvalidator_version": "2.2.1.dev36+gaa87b97", "vvdb_version": "vvdb_2022_11", "vvseqrepo_db": "VV_SR_2022_11/master", "vvta_version": "vvta_2022_11_1"}
}
```

So this morning I switched back to my docker internal servers.

**Comment by beboche** [comment]
Yes I'll remind you. Yes, this is intermittent, of course, it likely requires 2 simultaneous queries, then it occurs when the VV server is highly used.
And well, the thing is,  results are not always empty, my examples can be misleading on this point. For example,  in example 3 results where full for NM_005228.3:c.2236_2250del (while query was NM_001009944.3:c.10970C>T).
